name: Create release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Build plugin
        run: |
          npm ci
          npm run build
      - name: Generate attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            out/main.js
            out/styles.css
            out/manifest.json
      - name: Release plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            out/main.js out/manifest.json out/styles.css